name: Notifying Browserstack and slack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Fetch Latest Stable Chrome Version
      run: |
          LATEST_STABLE_CHROME_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE)
          echo "LATEST_STABLE_CHROME_VERSION=$LATEST_STABLE_CHROME_VERSION" >> $GITHUB_ENV
          
    - name: Download ChromeDriver Matching Latest Stable Chrome
      run: |
          mkdir -p resources/webDrivers
          CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/${{ env.LATEST_STABLE_CHROME_VERSION }}/linux64/chromedriver-linux64.zip"
          curl -s -o chromedriver.zip "$CHROMEDRIVER_URL"
          unzip -q chromedriver.zip -d resources/webDrivers
          mv resources/webDrivers/chromedriver-linux64/chromedriver resources/webDrivers/
          chmod +x resources/webDrivers/chromedriver
          ls -la resources/webDrivers/
  
    - name: Install Google Chrome
      run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
  
    - name: Run Tests on BrowserStack
      run: mvn clean test
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        BROWSERSTACK_BUILD_NAME: "Notifying Browserstack and slack"
        BROWSERSTACK_PROJECT_NAME: "My First Github Actions POC"
        FRAMEWORK: testng
        TEST_OBSERVABILITY: true

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


